rabbit:
  image: rabbitmq
  name: rabbitmq
  ports:
   - "5672:5672"
cp_intake:
  image: otherwhitefrank/cp_intake
  name: cp_intake
  ports:
   - "3000:3000"
  links:
   - rabbit
  volumes:
   - ./logs:/api/logs/
odns_upload:
  image: otherwhitefrank/odns_upload
  name: odns_upload
  links:
   - rabbit
  volumes:
   - ./logs:/api/logs/

